# This file defines the list of Applications to serve
# Use the unique id from the persons.toml file when defining the author and owner.
[home]
name = "Home"
introduction = "The landing page of the site"
description = "The landing page introduces the site and provides navigation"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "/"
servable = "src/apps/home/app.py"
thumbnail_url = "assets/images/thumbnails/home.png"
tags = []
category = "Main"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[gallery]
name = "Gallery"
introduction = "An overview of all apps"
description = "The purpose of the Gallery is to enable you to get inspiration and locate the app you need"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "gallery"
servable = "src/apps/gallery/app.py"
thumbnail_url = "assets/images/thumbnails/gallery.png"
tags = []
category = "Main"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_world_from_notebook_file]
name = "Hello World from notebook File"
introduction = "A very simple Hello World app deployed from a .ipynb NOTEBOOK"
description = "A very simple Hello World app deployed from a .ipynb NOTEBOOK"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-world-from-notebook"
servable = "src/apps/hello_world/app.ipynb"
thumbnail_url = "assets/images/thumbnails/hello-world.png"
tags = []
category = "Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_world_from_python_file]
name = "Hello World from Python File"
introduction = "A very simple Hello World app deployed from a .py FILE"
description = "A very simple Hello World app deployed from a .py FILE"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-world-from-file"
servable = "src/apps/hello_world/app.py"
thumbnail_url = "assets/images/thumbnails/hello-world.png"
tags = []
category = "Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[holoviews_linked_selections]
name = "HoloViews Linked Selections"
introduction = "A demonstration of HoloViews linked selections for Bokeh and Plotly backends"
description = "Returns an example app using the OrstedGalleryTemplate"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "holoviews-linked-selections"
servable = "src/apps/holoviews_linked_selections/app.py"
thumbnail_url = "assets/images/thumbnails/holoviews-linked-selections.png"
tags = []
category = "Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/holoviews_linked_brushing.py"
mp4_url = "assets/videos/mp4s/holoviews-linked-selections.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""

[streaming_dashboard]
name = "Streaming Dashboard"
introduction = "A demonstration of a Streaming Dashboard"
description = "A demonstration of a Streaming Dashboard"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "streaming-dashboard"
servable = "src/apps/streaming_dashboard/app.py"
thumbnail_url = "assets/images/thumbnails/streaming-dashboard.png"
tags=["Streaming", "Dashboard", "StatsCard"]
category = "Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/streaming_dashboard/app.py"
mp4_url = "assets/videos/mp4s/streaming-dashboard.mp4.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""

[streaming_plots]
name = "Streaming plots"
introduction = "A demonstration of a Streaming plots"
description = "A demonstration of a Streaming plots"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "streaming-plots"
servable = "src/apps/streaming_plots/app.py"
thumbnail_url = "assets/images/thumbnails/streaming-plots.png"
tags=["Streaming", "Streamz", "Plots"]
category = "Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/streaming_plots/app.py"
mp4_url = "assets/videos/mp4s/streaming-plots.mp4.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""