# This file defines the list of Applications to serve
[home]
name = "Home"
introduction = "The landing page of the site"
description = "The landing page introduces the site and provides navigation"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "/"
servable = "src/apps/home/home.py"
thumbnail_url = "assets/images/thumbnails/home.png"
tags = []
category = "Application"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[gallery]
name = "Gallery"
introduction = "An overview of all apps"
description = "The purpose of the Gallery is to enable you to get inspiration and locate the app you need"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "gallery"
servable = "src/apps/gallery.py"
thumbnail_url = "assets/images/thumbnails/gallery.png"
tags = []
category = "Application"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_world_from_notebook_file]
name = "Hello World from notebook File"
introduction = "A very simple Hello World app deployed from a NOTEBOOK"
description = "A very simple Hello World app deployed from a notebook"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-world-from-notebook"
servable = "src/apps/hello_world.ipynb"
thumbnail_url = "assets/images/thumbnails/hello-world.png"
tags = []
category = "Application"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_world_from_py_file]
name = "Hello World from .py File"
introduction = "A very simple Hello World app deployed from a .py FILE"
description = "A very simple Hello World app deployed from a .py file"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-world-from-file"
servable = "src/apps/hello_world.py"
thumbnail_url = "assets/images/thumbnails/hello-world.png"
tags = []
category = "Application"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[holoviews_linked_selections]
name = "HoloViews Linked Selections"
introduction = "A demonstration of HoloViews linked selections for Bokeh and Plotly backends"
description = "Returns an example app using the OrstedGalleryTemplate"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "holoviews-linked-selections"
servable = "src/apps/holoviews_linked_selections.py"
thumbnail_url = "assets/images/thumbnails/holoviews-linked-selections.png"
tags = []
category = "Application"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-panel-starter/blob/main/src/apps/holoviews_linked_brushing.py"
mp4_url = "assets/videos/mp4s/holoviews-linked-selections.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""