apiVersion: v1
kind: Service
metadata:
  name: us-trading-panel
  namespace: odl-trading-analytics-ns
  labels:
    app: us-trading-panel
    env: dev
spec:
  ports:
  - port: 80
    targetPort: 5007
    protocol: TCP
  selector:
    app: us-trading-panel
    env: dev