apiVersion: v1
kind: Service
metadata:
  name: awesome-analytics-apps-site
  namespace: <your-namespace-here>
  labels:
    app: awesome-analytics-apps-site
    env: prod
spec:
  ports:
  - port: 80
    targetPort: 5007
    protocol: TCP
  selector:
    app: awesome-analytics-apps-site
    env: prod